version: "3"
services:
  knave_in:
    build: .
    restart: always

  influx_knave:
    restart: always
    image: influxdb

  knave_out:
    build: knave_out
    ports:
        - "4432:4432"
    restart: always
